name: InfernalMobs
main: com.jacob_vejvoda.infernal_mobs.InfernalMobs
version: 5.1
depend: [NyaaCore]
softdepend: [Vault]
api-version: 1.13
commands:
  infernalmobs:
    aliases: [im]
    description: This is the infernal mobs base commands.
    usage: /<command>
    permission: infernal_mobs.commands
    permission-message: You don't have <permission>
  infernalinfo:
    aliases: [imi]
    description: Toggle infernal mob kill broadcast
    usage: /imi <mode>
    permission: infernal_mobs.imi
    permission-message: You don't have <permission>

permissions:
  infernal_mobs.commads:
    description: infernal mob's admin command
    default: op
  infernal_mobs.imi:
    description: switch between different broadcast receive modes.
    default: true
